### ISSUE TITLE
Unable to create Azure Account

### ISSUE THREAD

**Issue by raomohsinkhan** [yorek/azure-sql-db-samples#2]
Hi Yorek,

I am following this tutorial 
https://docs.microsoft.com/en-us/samples/azure-samples/azure-sql-db-python-rest-api/azure-sql-db-python-rest-api/
I have to install sample database 
https://github.com/yorek/azure-sql-db-samples#restore-wideworldimporters-database
Here 
-------------------------------
Make sure you have an Azure SQL DB database to use. If you don't have an Azure account you, you can create one for free that will also include a free Azure SQL DB tier:

https://azure.microsoft.com/en-us/free/free-account-faq/

To create a new database, follow the instructions here:
-------------------------------
When I am trying to create free account it ask me to verify by card. I don't have card. so I am unable to create Azure free account. Is there any other way to complete this tutorial?
can I find a username and password for sampledb (WideWorldImporters) database?

I am looking forward to hearing from you soon.

Many thanks,
Rao

**Comment by yorek** [comment]
Is the student option something you can take advantage of: https://azure.microsoft.com/en-us/free/students/ ?

**Comment by raomohsinkhan** [comment]
Hi Yorek,

No I am still unable to create student account

 Academic verification required
The account you are signed in is not yet verified to access offer benefits. Please use the form below to verify.
Verification method 

School Name

Enter a valid school name

------------------
From Pakistan, we are unable to create azure account. The free Azure accounts are only for Europe or US.....
